name: Deploy Static Next.js with Bun

on:
  push:
    branches:
      - main # Or your desired branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest # Or a specific version like '1.2.0'

      - name: Install dependencies
        run: bun install

      - name: Build Next.js static export
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Or your custom output directory if `distDir` was changed
